### ISSUE TITLE
Build with Gradle information

### ISSUE THREAD

**Issue by serut** [tommysiu/spring-data-gae#1]
I had several issue when I started to work around your code :
Your gradle configuration does not work with the lastest version of gradle, so I get gradle-2-2-1 version and script was correctly handled.

I needed to configure the path APPENGINE_HOME :  

```
      export APPENGINE_HOME=/Applications/DevTools/appengine-java-sdk-1.9.19/
```

I had to edit the _gradle.conf_ file to the lastest version of Google App Engine :  

```
  appEngineSdkVersion = '1.9.6'  
  to  
  appEngineSdkVersion = '1.9.19'
```

and finally if you still get an error, like this one : http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18037#p76643 , but you juste need to replace :  

```
  minusConfigurations += configurations.compile  
  to  
  minusConfigurations += [ project.configurations.compile ] 
```

**Comment by tommysiu** [comment]
Thanks serut. I totally missed that before.
